<a href="https://colab.research.google.com/github/victor1cg/Python/blob/master/Algoritmo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**# Avaliação Confitec #**

##### Nome : Victor Goncalves
##### Data : 13/03/2022
#### -------- Algoritmo --------


In [1]:
import pandas as pd
import numpy as np
from numpy import random

In [3]:
# definindo a funcao e setando random.seed
%time
def mult_matrix (x):
  np.random.seed(123)
  A = np.random.randint(100, size=(x, x))
  
  np.random.seed(10)
  B = np.random.randint(100, size=(x, x)) 

  Y = np.dot(A,B)
  return (print(f'\nMatrix A:\n {A}\n\nMatrix B:\n {B} \n\nO produto de A e B:\n {Y}'))

mult_matrix(3)

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 6.68 µs

Matrix A:
 [[66 92 98]
 [17 83 57]
 [86 97 96]]

Matrix B:
 [[ 9 15 64]
 [28 89 93]
 [29  8 73]] 

O produto de A e B:
 [[ 6012  9962 19934]
 [ 4130  8098 12968]
 [ 6274 10691 21533]]
